#Base image
FROM node:lts-alpine
LABEL maintainer "Ulrich Genske"

# Set the working directory
WORKDIR /home/frontend

# Copy the package.json and package-lock.json
COPY package*.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY vue.config.js ./
COPY babel.config.js ./
COPY .eslintrc.js ./


# install project dependencies
RUN npm i -g npm@8.5.1
RUN npm install

# Expose a port
EXPOSE 8080

# start dev server
CMD [ "npm", "run", "serve" ]