#Base image
FROM hon_vue_dev
LABEL maintainer "Ulrich Genske"

# Set the working directory
WORKDIR /home/frontend

# Copy the code
COPY src /home/frontend/src
COPY public /home/frontend/public

# build project
RUN npm run build

RUN rm -r /home/frontend/src
RUN rm -r /home/frontend/public

# install ngnix
RUN apk --no-cache update \
&& apk --no-cache upgrade \
&& apk --no-cache add nginx

# copy ngnix config
COPY docker/nginx.conf /etc/nginx/nginx.conf
# test ngnix config, returns error during build but not on up => deactivated for now
# RUN nginx -t

# start server
COPY docker/entrypoint_prod.sh /entry.sh
RUN ["chmod","+x","/entry.sh"]
CMD /entry.sh