version: '3.9'
services:
  app:
    container_name: HON_dev
    image: hon_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile_dev
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # only needed for external mysql db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    volumes:
      - './app:/home/HON/app'
      - './instance:/home/HON/instance'
    stdin_open: true
    tty: true
