version: "3.9"
services:
  app:
    container_name: HON_prod
    image: hon_prod  
    build: 
      context: .
      dockerfile: ./docker/Dockerfile_prod
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      # Keeps Python from generating .pyc files in the container
      - PYTHONDONTWRITEBYTECODE=1
      # Turns off buffering for easier container logging
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes: 
      - './logs:/var/log/'
      - './instance:/home/HON/instance'
