version: "3.9"
services:
  app:
    container_name: HON_dev
    image: hon_dev  
    build: 
      context: .
      dockerfile: ./docker/Dockerfile_dev
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DB_HOST=/home/HON/instance
      - DB_TYPE=sqlite
      - DB_NAME=dev.db
      # Keeps Python from generating .pyc files in the container
      - PYTHONDONTWRITEBYTECODE=1
      # Turns off buffering for easier container logging
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes: 
      - './app:/home/HON/app'
      - './logs:/var/log/'
      - './instance:/home/HON/instance'
    stdin_open: true
    tty: true
