version: '3.9'
name: 'hon_development'

services:
  backend:
    container_name: hon_flask_api_dev
    image: hon_flask_api_dev
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile_dev
    environment:
      - FLASK_APP=flask_api
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # only needed if mysql db runs outisde of docker container on host machine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      # debug port vscode
      - 5678:5678
    volumes:
      - './backend/flask_api:/home/backend/flask_api'      
      - './instance:/home/backend/instance'
    stdin_open: true
    tty: true
  frontend:
    container_name: hon_vue_dev
    image: hon_vue_dev
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile_dev
    ports:
      - 8080:8080
    volumes:
      - './frontend/src:/home/frontend/src'
      - './frontend/public:/home/frontend/public'
