version: "3.9"
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      # Keeps Python from generating .pyc files in the container
      - PYTHONDONTWRITEBYTECODE 1
      # Turns off buffering for easier container logging
      - PYTHONUNBUFFERED 1
    volumes: 
      - './:/home/HON'
    command: flask run --host 0.0.0.0
    ports:
      - "5000:5000"
