version: "3.9"
services:
  app:
    container_name: HON_prod
    image: hon_prod  
    build: 
      context: .
      dockerfile: ./docker/Dockerfile_prod
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # only needed for external mysql db
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
    volumes: 
      - './logs:/var/log/'
      - './instance:/home/HON/instance'
