FROM alpine:3.14
LABEL maintainer "Ulrich Genske <uli.genske@gmail.com>"
WORKDIR /home/HON
RUN mkdir /home/HON/instance
RUN mkdir /home/HON/instance/images

# install python req
RUN  apk --no-cache update \
  && apk --no-cache upgrade \
  && apk --no-cache add py3-pip tzdata py3-wheel inotify-tools python3-dev gcc g++ geos-dev mariadb-dev musl-dev py3-pandas
COPY requirements.txt /home/HON
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
 && echo "Europe/Berlin" > /etc/timezone

# copy config
COPY config.py /home/HON/config.py

# use flask dev sever during development
EXPOSE 80
CMD flask run --host=0.0.0.0 --port=80