FROM hon_dev
LABEL maintainer "Ulrich Genske <uli.genske@gmail.com>"
WORKDIR /home/HON

# copy flask app
COPY app /home/HON/app

# download js and css dependencies
COPY get_js_dep.sh /home/HON
RUN ["chmod","+x","get_js_dep.sh"]
RUN ./get_js_dep.sh

# install gunicorn and ngnix
RUN  apk --no-cache update \
  && apk --no-cache upgrade \
  && apk --no-cache add nginx py3-gunicorn

# setup gunicorn and nginx
COPY wsgi.py /home/HON/wsgi.py
COPY docker/nginx.conf /etc/nginx/nginx.conf
RUN nginx -t
COPY docker/entrypoint.sh /entry.sh
RUN ["chmod","+x","/entry.sh"]
CMD /entry.sh