FROM hon_flask_api_dev
LABEL maintainer "Ulrich Genske <uli.genske@gmail.com>"
WORKDIR /home/backend

# copy config
COPY config.py /home/backend/config.py

# copy flask app code
COPY flask_api /home/backend/flask_api

# install gunicorn 
RUN  apk --no-cache update \
  && apk --no-cache upgrade \
  && apk --no-cache add py3-gunicorn

# setup gunicorn 
COPY wsgi.py /home/backend/wsgi.py

# start prod server
COPY docker/entrypoint_prod.sh /entry.sh
RUN ["chmod","+x","/entry.sh"]
CMD /entry.sh